-- Seed data for states & districts (India). Generated for dev/demo use.
SET FOREIGN_KEY_CHECKS=0;
DELETE FROM districts;
DELETE FROM states;
ALTER TABLE states AUTO_INCREMENT = 1;
ALTER TABLE districts AUTO_INCREMENT = 1;

INSERT INTO states (id, name) VALUES
(1, 'Andaman and Nicobar Islands'),
(2, 'Andhra Pradesh'),
(3, 'Arunachal Pradesh'),
(4, 'Assam'),
(5, 'Bihar'),
(6, 'Chandigarh'),
(7, 'Chhattisgarh'),
(8, 'Dadra and Nagar Haveli and Daman and Diu'),
(9, 'Delhi'),
(10, 'Goa'),
(11, 'Gujarat'),
(12, 'Haryana'),
(13, 'Himachal Pradesh'),
(14, 'Jammu and Kashmir'),
(15, 'Jharkhand'),
(16, 'Karnataka'),
(17, 'Kerala'),
(18, 'Ladakh'),
(19, 'Lakshadweep'),
(20, 'Madhya Pradesh'),
(21, 'Maharashtra'),
(22, 'Manipur'),
(23, 'Meghalaya'),
(24, 'Mizoram'),
(25, 'Nagaland'),
(26, 'Odisha'),
(27, 'Puducherry'),
(28, 'Punjab'),
(29, 'Rajasthan'),
(30, 'Sikkim'),
(31, 'Tamil Nadu'),
(32, 'Telangana'),
(33, 'Tripura'),
(34, 'Uttar Pradesh'),
(35, 'Uttarakhand'),
(36, 'West Bengal');

INSERT INTO districts (state_id, name) VALUES
(1, 'South Andaman'),
(1, 'North and Middle Andaman'),
(1, 'Nicobar'),
(2, 'Anantapur'),
(2, 'Chittoor'),
(2, 'East Godavari'),
(2, 'Guntur'),
(2, 'Krishna'),
(2, 'Kurnool'),
(2, 'Nellore'),
(2, 'Prakasam'),
(2, 'Srikakulam'),
(2, 'Visakhapatnam'),
(2, 'Vizianagaram'),
(2, 'West Godavari'),
(2, 'Kadapa'),
(2, 'Tirupati'),
(2, 'Kakinada'),
(3, 'Tawang'),
(3, 'West Kameng'),
(3, 'East Kameng'),
(3, 'Papum Pare'),
(3, 'Lower Subansiri'),
(3, 'Upper Subansiri'),
(3, 'West Siang'),
(3, 'East Siang'),
(3, 'Lohit'),
(3, 'Changlang'),
(3, 'Tirap'),
(3, 'Lower Dibang Valley'),
(3, 'Upper Dibang Valley'),
(3, 'Kurung Kumey'),
(3, 'Namsai'),
(4, 'Kamrup'),
(4, 'Kamrup Metropolitan'),
(4, 'Dibrugarh'),
(4, 'Jorhat'),
(4, 'Nagaon'),
(4, 'Sivasagar'),
(4, 'Tinsukia'),
(4, 'Barpeta'),
(4, 'Cachar'),
(4, 'Golaghat'),
(4, 'Darrang'),
(4, 'Dhemaji'),
(4, 'Dhubri'),
(4, 'Goalpara'),
(4, 'Karimganj'),
(4, 'Lakhimpur'),
(4, 'Nalbari'),
(4, 'Sonitpur'),
(5, 'Patna'),
(5, 'Gaya'),
(5, 'Bhagalpur'),
(5, 'Muzaffarpur'),
(5, 'Darbhanga'),
(5, 'Purnia'),
(5, 'Nalanda'),
(5, 'Rohtas'),
(5, 'Saran'),
(5, 'Vaishali'),
(5, 'Begusarai'),
(5, 'Samastipur'),
(5, 'Munger'),
(5, 'West Champaran'),
(5, 'East Champaran'),
(5, 'Nawada'),
(5, 'Katihar'),
(6, 'Chandigarh'),
(7, 'Raipur'),
(7, 'Bilaspur'),
(7, 'Durg'),
(7, 'Korba'),
(7, 'Raigarh'),
(7, 'Rajnandgaon'),
(7, 'Bastar'),
(7, 'Dhamtari'),
(7, 'Janjgir-Champa'),
(7, 'Kabirdham'),
(7, 'Kanker'),
(7, 'Koriya'),
(7, 'Mahasamund'),
(7, 'Surguja'),
(7, 'Jashpur'),
(8, 'Dadra and Nagar Haveli'),
(8, 'Daman'),
(8, 'Diu'),
(9, 'New Delhi'),
(9, 'North Delhi'),
(9, 'South Delhi'),
(9, 'East Delhi'),
(9, 'West Delhi'),
(9, 'Central Delhi'),
(9, 'North East Delhi'),
(9, 'North West Delhi'),
(9, 'South East Delhi'),
(9, 'South West Delhi'),
(9, 'Shahdara'),
(10, 'North Goa'),
(10, 'South Goa'),
(11, 'Ahmedabad'),
(11, 'Surat'),
(11, 'Vadodara'),
(11, 'Rajkot'),
(11, 'Bhavnagar'),
(11, 'Jamnagar'),
(11, 'Junagadh'),
(11, 'Gandhinagar'),
(11, 'Anand'),
(11, 'Bharuch'),
(11, 'Kutch'),
(11, 'Mehsana'),
(11, 'Navsari'),
(11, 'Patan'),
(11, 'Porbandar'),
(11, 'Valsad'),
(12, 'Faridabad'),
(12, 'Gurugram'),
(12, 'Panipat'),
(12, 'Ambala'),
(12, 'Karnal'),
(12, 'Hisar'),
(12, 'Rohtak'),
(12, 'Sonipat'),
(12, 'Yamunanagar'),
(12, 'Panchkula'),
(12, 'Sirsa'),
(12, 'Bhiwani'),
(12, 'Jind'),
(12, 'Kaithal'),
(12, 'Kurukshetra'),
(13, 'Shimla'),
(13, 'Kangra'),
(13, 'Mandi'),
(13, 'Solan'),
(13, 'Una'),
(13, 'Bilaspur'),
(13, 'Chamba'),
(13, 'Hamirpur'),
(13, 'Kinnaur'),
(13, 'Kullu'),
(13, 'Lahaul and Spiti'),
(13, 'Sirmaur'),
(14, 'Srinagar'),
(14, 'Jammu'),
(14, 'Anantnag'),
(14, 'Baramulla'),
(14, 'Budgam'),
(14, 'Pulwama'),
(14, 'Kupwara'),
(14, 'Kathua'),
(14, 'Udhampur'),
(14, 'Rajouri'),
(15, 'Ranchi'),
(15, 'Dhanbad'),
(15, 'Jamshedpur (East Singhbhum)'),
(15, 'Bokaro'),
(15, 'Deoghar'),
(15, 'Hazaribagh'),
(15, 'Giridih'),
(15, 'Palamu'),
(15, 'Ramgarh'),
(15, 'Dumka'),
(15, 'Chatra'),
(15, 'Garhwa'),
(16, 'Bengaluru Urban'),
(16, 'Bengaluru Rural'),
(16, 'Mysuru'),
(16, 'Belagavi'),
(16, 'Hubballi-Dharwad'),
(16, 'Mangaluru (Dakshina Kannada)'),
(16, 'Kalaburagi'),
(16, 'Ballari'),
(16, 'Shivamogga'),
(16, 'Tumakuru'),
(16, 'Davangere'),
(16, 'Bidar'),
(16, 'Bijapur (Vijayapura)'),
(16, 'Udupi'),
(16, 'Chikkamagaluru'),
(16, 'Raichur'),
(17, 'Thiruvananthapuram'),
(17, 'Kollam'),
(17, 'Pathanamthitta'),
(17, 'Alappuzha'),
(17, 'Kottayam'),
(17, 'Idukki'),
(17, 'Ernakulam'),
(17, 'Thrissur'),
(17, 'Palakkad'),
(17, 'Malappuram'),
(17, 'Kozhikode'),
(17, 'Wayanad'),
(17, 'Kannur'),
(17, 'Kasaragod'),
(18, 'Leh'),
(18, 'Kargil'),
(19, 'Lakshadweep'),
(20, 'Bhopal'),
(20, 'Indore'),
(20, 'Gwalior'),
(20, 'Jabalpur'),
(20, 'Ujjain'),
(20, 'Sagar'),
(20, 'Satna'),
(20, 'Rewa'),
(20, 'Ratlam'),
(20, 'Dewas'),
(20, 'Chhindwara'),
(20, 'Vidisha'),
(20, 'Sehore'),
(20, 'Betul'),
(20, 'Hoshangabad'),
(20, 'Khandwa'),
(20, 'Khargone'),
(21, 'Mumbai City'),
(21, 'Mumbai Suburban'),
(21, 'Pune'),
(21, 'Nagpur'),
(21, 'Nashik'),
(21, 'Thane'),
(21, 'Aurangabad'),
(21, 'Solapur'),
(21, 'Kolhapur'),
(21, 'Amravati'),
(21, 'Nanded'),
(21, 'Sangli'),
(21, 'Satara'),
(21, 'Ahmednagar'),
(21, 'Latur'),
(21, 'Akola'),
(21, 'Jalgaon'),
(21, 'Raigad'),
(22, 'Imphal East'),
(22, 'Imphal West'),
(22, 'Thoubal'),
(22, 'Bishnupur'),
(22, 'Churachandpur'),
(22, 'Senapati'),
(22, 'Ukhrul'),
(22, 'Tamenglong'),
(22, 'Chandel'),
(23, 'East Khasi Hills'),
(23, 'West Khasi Hills'),
(23, 'Ri Bhoi'),
(23, 'East Garo Hills'),
(23, 'West Garo Hills'),
(23, 'Jaintia Hills'),
(24, 'Aizawl'),
(24, 'Lunglei'),
(24, 'Champhai'),
(24, 'Kolasib'),
(24, 'Mamit'),
(24, 'Serchhip'),
(24, 'Lawngtlai'),
(24, 'Saiha'),
(25, 'Kohima'),
(25, 'Dimapur'),
(25, 'Mokokchung'),
(25, 'Tuensang'),
(25, 'Wokha'),
(25, 'Zunheboto'),
(25, 'Mon'),
(25, 'Phek'),
(26, 'Bhubaneswar (Khordha)'),
(26, 'Cuttack'),
(26, 'Puri'),
(26, 'Ganjam'),
(26, 'Sambalpur'),
(26, 'Rourkela (Sundargarh)'),
(26, 'Balasore'),
(26, 'Mayurbhanj'),
(26, 'Kalahandi'),
(26, 'Koraput'),
(26, 'Bolangir'),
(26, 'Angul'),
(27, 'Puducherry'),
(27, 'Karaikal'),
(27, 'Mahe'),
(27, 'Yanam'),
(28, 'Ludhiana'),
(28, 'Amritsar'),
(28, 'Jalandhar'),
(28, 'Patiala'),
(28, 'Bathinda'),
(28, 'Mohali'),
(28, 'Hoshiarpur'),
(28, 'Ferozepur'),
(28, 'Moga'),
(28, 'Sangrur'),
(28, 'Kapurthala'),
(28, 'Gurdaspur'),
(29, 'Jaipur'),
(29, 'Jodhpur'),
(29, 'Udaipur'),
(29, 'Kota'),
(29, 'Ajmer'),
(29, 'Bikaner'),
(29, 'Alwar'),
(29, 'Bharatpur'),
(29, 'Sikar'),
(29, 'Bhilwara'),
(29, 'Pali'),
(29, 'Sri Ganganagar'),
(29, 'Nagaur'),
(29, 'Churu'),
(29, 'Jaisalmer'),
(30, 'East Sikkim'),
(30, 'West Sikkim'),
(30, 'North Sikkim'),
(30, 'South Sikkim'),
(31, 'Chennai'),
(31, 'Coimbatore'),
(31, 'Madurai'),
(31, 'Tiruchirappalli'),
(31, 'Salem'),
(31, 'Tirunelveli'),
(31, 'Erode'),
(31, 'Vellore'),
(31, 'Thanjavur'),
(31, 'Tiruppur'),
(31, 'Dindigul'),
(31, 'Kanchipuram'),
(31, 'Cuddalore'),
(31, 'Thoothukudi'),
(31, 'Nagercoil (Kanyakumari)'),
(32, 'Hyderabad'),
(32, 'Warangal'),
(32, 'Nizamabad'),
(32, 'Karimnagar'),
(32, 'Khammam'),
(32, 'Ramagundam'),
(32, 'Mahbubnagar'),
(32, 'Nalgonda'),
(32, 'Adilabad'),
(32, 'Medak'),
(32, 'Rangareddy'),
(32, 'Siddipet'),
(33, 'West Tripura'),
(33, 'South Tripura'),
(33, 'North Tripura'),
(33, 'Dhalai'),
(33, 'Khowai'),
(33, 'Sepahijala'),
(33, 'Gomati'),
(33, 'Unakoti'),
(34, 'Lucknow'),
(34, 'Kanpur'),
(34, 'Agra'),
(34, 'Varanasi'),
(34, 'Meerut'),
(34, 'Prayagraj'),
(34, 'Ghaziabad'),
(34, 'Noida (Gautam Buddh Nagar)'),
(34, 'Bareilly'),
(34, 'Aligarh'),
(34, 'Moradabad'),
(34, 'Saharanpur'),
(34, 'Gorakhpur'),
(34, 'Jhansi'),
(34, 'Mathura'),
(34, 'Firozabad'),
(34, 'Muzaffarnagar'),
(35, 'Dehradun'),
(35, 'Haridwar'),
(35, 'Nainital'),
(35, 'Udham Singh Nagar'),
(35, 'Almora'),
(35, 'Pauri Garhwal'),
(35, 'Tehri Garhwal'),
(35, 'Chamoli'),
(35, 'Pithoragarh'),
(35, 'Champawat'),
(35, 'Bageshwar'),
(35, 'Rudraprayag'),
(35, 'Uttarkashi'),
(36, 'Kolkata'),
(36, 'Howrah'),
(36, 'North 24 Parganas'),
(36, 'South 24 Parganas'),
(36, 'Hooghly'),
(36, 'Nadia'),
(36, 'Murshidabad'),
(36, 'Purba Bardhaman'),
(36, 'Paschim Bardhaman'),
(36, 'Darjeeling'),
(36, 'Malda'),
(36, 'Jalpaiguri'),
(36, 'Cooch Behar'),
(36, 'Purulia'),
(36, 'Bankura');

SET FOREIGN_KEY_CHECKS=1;
